using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace ForgeBot.Tools
{
    public enum Item : ushort
    {
        None,
        Grass,
        Dirt,
        Sand,
        Scoria,
        Wood,
        WoodPlank,
        WoodVeneer,
        Leaves,
        Glass,
        Cloud,
        Water,
        Copper,
        Lava,
        Cassiterite,
        Clay,
        Sandstone,
        Limestone,
        Basalt,
        Andesite,
        Dacite,
        Diorite,
        Tuff,
        Serpentine,
        Gabbro,
        Granite,
        Komatiite,
        Marble,
        Rhyolite,
        Bedrock,
        Carbon,
        Obsidian,
        Coal,
        Flint,
        Greenstone,
        Diamond,
        Ruby,
        Gold,
        Platinum,
        Iron,
        Opal,
        Uranium,
        Cobblestone,
        Bricks,
        Chess,
        Bookcase,
        Torch,
        Ladder,
        Workbench,
        Furnace,
        Chest,
        WoodDoorTop,
        SteelDoorTop,
        Teleport,
        TNT,
        C4,
        Wisdom,
        Blueprint,
        Sapling,
        WhiteFlowers,
        PurpleFlowers,
        RedFlowers,
        YellowFlowers,
        PineLeaves,
        ItemShop,
        BlockShop,
        Sulphur,
        Cyclonite,
        Titanium,
        Teflon,
        Fluorite,
        WovenLeaves,
        Rope,
        MultiTextureBlock,
        MossyCobblestone,
        Pane,
        StainedGlassPane,
        Post,
        HealthBlock,
        GrassyStone,
        BlueBox,
        CustomBlock1,
        CustomBlock2,
        CustomBlock3,
        CustomBlock4,
        CustomBlock5,
        CustomBlock6,
        CustomBlock7,
        CustomBlock8,
        CustomBlock9,
        CustomBlock10,
        UserDefined1,
        UserDefined2,
        UserDefined3,
        UserDefined4,
        UserDefined5,
        UserDefined6,
        UserDefined7,
        UserDefined8,
        UserDefined9,
        VoidMarker,
        Rasta,
        WhiteTile,
        Checkered,
        Retro,
        CherryMetal,
        Static,
        Ice,
        ConcreteBrick,
        Turkish,
        Camouflage,
        SpiderEgg,
        LongGrass,
        Stairs,
        AmbientSoundBlock,
        WoodDoorBottom,
        SteelDoorBottom,
        Sign,
        Fire,
        SteelSpikes,
        ClimbingIvy,
        Book,
        Key,
        RaresChest,
        Crop,
        InvisibleBarrier,
        CoverBlock,
        RedMushroom,
        ArcadeMachine,
        ParticleEmitter,
        Stack,
        UpsideDownStack,
        LockedChest,
        LitFurnace,
        WhiteWool,
        BedHead,
        BedFoot,
        NPCSpawn,
        Crate,
        Fence,
        LockedDoorTop,
        SunBox,
        SentryTurret,
        ProximityDetector,
        Snow,
        SnowLayer,
        Scaffold,
        SteelPortcullis,
        SteelPlating,
        HalfBlock,
        Ramp,
        Cactus,
        TerracottaTile,
        OneWayGlass,
        Cylinder,
        GoldBlock,
        StoneWall,
        SandBrick,
        Table,
        GildedWoodPanel,
        Painting,
        GrassShaded,
        MapleLeaves,
        WifiTransmitter,
        WifiReceiver,
        PressurePlate,
        PoweredLight,
        Safe,
        Sundial,
        Switch,
        Button,
        TrapDoor,
        ScriptBlock,
        TilledEarth,
        SaltBlock,
        EntitySpawn,
        Bone,
        Sapphire,
        StoneBrick,
        BirchWood,
        BirchWoodPlank,
        StainedGlass,
        Unused1,
        Unused2,
        Unused3,
        Unused4,
        Unused5,
        SidePost,
        Unused6,
        CornerBlock,
        Unused7,
        Unused8,
        PolishedBasalt,
        PolishedAndesite,
        PolishedDacite,
        PolishedDiorite,
        PolishedTuff,
        PolishedSerpentine,
        PolishedGabbro,
        PolishedGranite,
        PolishedKomatiite,
        PolishedMarble,
        PolishedRhyolite,
        PolishedGreenstone,
        LockedDoorBottom,
        PolishedBasaltBrick,
        PolishedAndesiteBrick,
        PolishedDaciteBrick,
        PolishedDioriteBrick,
        PolishedTuffBrick,
        PolishedSerpentineBrick,
        PolishedGabbroBrick,
        PolishedGraniteBrick,
        PolishedKomatiiteBrick,
        PolishedMarbleBrick,
        PolishedRhyoliteBrick,
        PolishedGreenstoneBrick,
        Console,
        TechPanel,
        TechLamp,
        TechFurnace,
        PlasmaConduit,
        SteelVent,
        BerryBush,
        ColorSmoothGray,
        ColorBloodOrange,
        ColorLime,
        ColorLightTan,
        ColorLeather,
        ColorLightOrange,
        ColorLightYellow,
        ColorLightBlue,
        ColorDarkBlue,
        ColorLightGreen,
        ColorDarkBrown,
        ColorTan,
        ColorCreme,
        ColorDarkRed,
        ColorDarkGray,
        ColorGray,
        ColorDarkGreen,
        ColorPink,
        ColorPurple,
        ColorCyan,
        ColorBlack,
        ColorWhite,
        ColorYellow,
        ColorRed,
        ColorOrange,
        ColorLightBrown,
        ColorBrown,
        ColorGreen,
        ColorBlue,
        Marker,
        ExcludeMarker,
        zLastBlockID,
        Hand,
        WoodPickaxe,
        IronPickaxe,
        SteelPickaxe,
        DiamondPickaxe,
        RubyPickaxe,
        TitaniumPickaxe,
        WoodHatchet,
        IronHatchet,
        SteelHatchet,
        DiamondHatchet,
        WoodShovel,
        IronShovel,
        SteelShovel,
        DiamondShovel,
        WoodSpear,
        IronSpear,
        SteelSpear,
        DiamondSpear,
        WoodSword,
        IronSword,
        SteelSword,
        DiamondSword,
        Binoculars,
        Camera,
        Stick,
        IronIngot,
        SteelIngot,
        GoldBar,
        RubyGemStone,
        DiamondGemStone,
        GoldPieces,
        TitaniumIngot,
        GrenadeLauncher,
        Grenade,
        RawFish,
        CookedFish,
        Bucket,
        BucketOfWater,
        BucketOfLava,
        WoodShield,
        IronShield,
        SteelShield,
        DiamondShield,
        WoodDoor,
        SteelDoor,
        SledgeHammer,
        SignIcon,
        Lock,
        WoodBow,
        FlintArrow,
        Feather,
        FlintFlake,
        RawLambChops,
        CookedLambChops,
        RawDuckMeat,
        CookedDuckMeat,
        Bed,
        LockedDoor,
        Lighter,
        IronArrow,
        SteelArrow,
        DiamondArrow,
        RubyArrow,
        TitaniumArrow,
        BoomArrow,
        FireArrow,
        Clipboard,
        FenceIcon,
        RopeIcon,
        StairsIcon,
        HalfBlockIcon,
        RampIcon,
        CylinderIcon,
        SkeletonKey,
        SkullKey,
        SilkKey,
        DiamondKey,
        TitaniumKey,
        GoldKey,
        ShadowKey,
        DwarfKey,
        DarkKey,
        KeyOfLight,
        BobKey,
        StoneKey,
        GhostKey,
        TitanKey,
        HeroKey,
        LightningKey,
        LunaKey,
        SolarKey,
        CelestialKey,
        SlimeKey,
        NatureKey,
        UndeadKey,
        SpiderKey,
        FishKey,
        RubyKey,
        NauticalKey,
        TeleportKey,
        BattleAxe,
        ElvenBow,
        AmuletOfFlight,
        WaterTalisman,
        ShieldBadge,
        TenLeagueBoots,
        TableIcon,
        SwitchIcon,
        ButtonIcon,
        IronHoe,
        SteelHoe,
        DiamondHoe,
        IronScythe,
        SteelScythe,
        DiamondScythe,
        WheatSeed,
        SugarCaneSeed,
        Wheat,
        Sugar,
        Egg,
        Flour,
        Bottle,
        BottleOfWater,
        BottleOfMilk,
        BucketOfMilk,
        Dough,
        Bread,
        Cake,
        Butter,
        Cheese,
        Salt,
        Pizza,
        Tomato,
        IronBattleAxe,
        SteelBattleAxe,
        GreenstoneGoldBattleAxe,
        DiamondBattleAxe,
        RubyBattleAxe,
        TitaniumBattleAxe,
        PlatinumSword,
        RubySword,
        TitaniumSword,
        SteelScimitar,
        SteelPike,
        SteelClaymore,
        SteelKatana,
        GreenstoneGoldPickaxe,
        GreenstoneGoldHatchet,
        GreenstoneGoldShovel,
        GreenstoneGoldSword,
        GreenstoneGoldShield,
        GreenstoneGoldSledgeHammer,
        TomatoSeed,
        RawBeef,
        CookedBeef,
        CowHide,
        Leather,
        ObsidianGemStone,
        RingMould,
        AmuletMould,
        NecklaceMould,
        GoldRing,
        GoldAmulet,
        GoldNecklace,
        RingOfBob,
        AmuletOfFury,
        NecklaceOfKnowledge,
        SpiderRing,
        PredatorAmulet,
        NecklaceOfHypocrisy,
        RingOfExemption,
        AmuletOfStarlight,
        NecklaceOfFarsight,
        DiamantiumIngot,
        DiamantiumSword,
        Coif,
        LeatherBody,
        LeatherLeggings,
        LeatherHelmet,
        LeatherBoots,
        LeatherGauntlets,
        IronBody,
        IronLeggings,
        IronHelmet,
        IronBoots,
        IronGauntlets,
        SteelBody,
        SteelLeggings,
        SteelHelmet,
        SteelBoots,
        SteelGauntlets,
        DiamantiumBody,
        DiamantiumLeggings,
        DiamantiumHelmet,
        DiamantiumBoots,
        DiamantiumGauntlets,
        TitaniumBody,
        TitaniumLeggings,
        TitaniumHelmet,
        TitaniumBoots,
        TitaniumGauntlets,
        DiamantiumShield,
        TitaniumShield,
        SkillCombat,
        SkillHealth,
        SkillStrength,
        SkillAttack,
        SkillDefence,
        SkillRanged,
        SkillMining,
        SkillDigging,
        SkillChopping,
        SkillBuilding,
        SkillCrafting,
        SkillSmelting,
        SkillSmithing,
        SkillFarming,
        SkillCooking,
        SkillLooting,
        Splinter1,
        Splinter2,
        Splinter3,
        Splinter4,
        Splinter5,
        Splinter6,
        Splinter7,
        Splinter8,
        BoneMeal,
        Chance,
        IceArrow,
        SapphireGemStone,
        RingOfIce,
        UnknownAmulet,
        UnknownNecklace,
        TitaniumKatana,
        SkyWorld,
        SpaceWorld,
        TrollHide,
        TrollHideBody,
        TrollHideLeggings,
        TrollHideHelmet,
        TrollHideBoots,
        TrollHideGauntlets,
        GoldenBow,
        SpiderBow,
        TrollBow,
        TitaniumBow,
        NaturalWorld,
        FolderIcon,
        GrenadeTex,
        RubyWarHammer,
        TitaniumWarHammer,
        CopperIngot,
        TinIngot,
        BronzeIngot,
        BronzeHoe,
        BronzeScythe,
        BronzeArrow,
        BronzeSpear,
        BronzeSword,
        Chisel,
        Wand,
        ChatIcon,
        DecalApplicator,
        DarkStaff,
        LightStaff,
        SpiderStaff,
        NatureStaff,
        OceanStaff,
        NecromancerStaff,
        YliasterPotion,
        EitrPotion,
        IchorPotion,
        Revolver,
        EldarPistol,
        GoldenSMG,
        SpiderSMG,
        LaserBlaster,
        ComboAssaultRifle,
        SniperRifle,
        AssaultRifle,
        Shotgun,
        MiniGun,
        HeavyAssaultRifle,
        SemiAutoHandGun,
        PlasmaRifle,
        Bullet,
        MagicPotion,
        VaporPotion,
        EssenciaPotion,
        AstroPotion,
        EarthPotion,
        AestusFlask,
        DwarvenPotion,
        EctoplasmFlask,
        VolatileConcoction,
        SkoomaFlask,
        ResplendentMixture,
        KarmicPotion,
        Apple,
        Orange,
        Plum,
        Olives,
        Cherries,
        Strawberries,
        Blueberries,
        Banana,
        Lemon,
        Lime,
        Grapes,
        Raspberries,
        Gooseberries,
        Grapefruit,
        Blackberries,
        Unused9,
        Unused10,
        Unused11,
        Potato,
        Corn,
        Rosemary,
        Oregano,
        Thyme,
        Sage,
        Tarragon,
        Dill,
        Basil,
        BayLeaves,
        Parsley,
        Chives,
        Mint,
        Coriander,
        Majoram,
        Lavender,
        Fennel,
        Cornbread,
        PotatoPie,
        DebugTool,
        BlockReplacer,
        ObsidianShard,
        zLastItemID,
    }

    public class ItemDataXML
    {
        public Item ItemID;
        public string IDString;
        public string Name;
        public string Desc;
        public bool IsValid;
        public bool IsEnabled;
        public bool LockedDD;
        public bool LockedCR;
        public bool LockedSU;
        public bool HasItemProxy;
        public int MinCSPrice;
        public int StackSize;
        public ushort Durability;
        public float StrikeDamage;
        public float StrikeReach;
        public short HealPower;
        public ushort BurnTime;
        public float SmeltTime;
        public byte ParticleLight;
        public ItemSelectModeFlag SelectFlag;
        public bool CanDropIfLocked;
        public ushort DropChance;
        public PluralType Plural;
        public byte RarityLevel;
        public float Accuracy;
        public float ShotPower;
        public int MultiShot;
        public float ShotSpread;
        public float Piercing;
    }


    public class BlueprintXML
    {
        public Item ItemID;
        public BlueprintCraftType CraftType;
        public bool IsValid;
        public bool IsDefault;
        public short SortID;
        public Vector2 Depth;
        public InventoryItemNDXML Result;
        public InventoryItemXML Material11;
        public InventoryItemXML Material12;
        public InventoryItemXML Material13;
        public InventoryItemXML Material21;
        public InventoryItemXML Material22;
        public InventoryItemXML Material23;
        public InventoryItemXML Material31;
        public InventoryItemXML Material32;
        public InventoryItemXML Material33;
    }

    public enum PluralType : byte
    {
        None,
        S,
        ES,
    }

    public enum ItemRarityType : ushort
    {
        None,
        Rare
    }

    public enum BlueprintCraftType
    {
        Crafting,
        Furnace,
    }

    public struct InventoryItemXML
    {
        public Item ItemID;
        public ushort Durability;
        public int Count;

        public override string ToString()
        {
            return $"{ItemID} {Count}";
        }
    }


    public struct InventoryItemNDXML
    {
        public Item ItemID;
        public int Count;

        public override string ToString()
        {
            return $"{ItemID} {Count}";
        }
    }

    [Flags]
    public enum ItemSelectModeFlag : ushort
    {
        Fill = 0x01,
        MultiTexture = 0x02,
    }
}
